ALTER TABLE accounts
  MODIFY COLUMN type ENUM(
    'CONTA_CONJUNTA','CONTA_CORRENTE','CONTA_CREDITO','CONTA_DIGITAL',
    'CONTA_EMPRESARIAL','CONTA_ESTUDANTIL','CONTA_FIDELIDADE',
    'CONTA_INTERNACIONAL','CONTA_INVESTIMENTO','CONTA_POUPANCA',
    'CONTA_SALARIO','CONTA_UNIVERSITARIA'
  ) NOT NULL;